name: .Net Build CryptographyHelper

on:
  push:
    paths: 
      - 'src/CryptographyHelper/**'
  pull_request:
    paths: 
      - 'src/CryptographyHelper/**'
  workflow_dispatch:
  
jobs:
  build:

    defaults: 
      run:
        working-directory: src/CryptographyHelper
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.100

    - name: Test
      run: dotnet test CryptographyHelper.Tests/CryptographyHelper.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

    - name: Build
      run: dotnet build --configuration Release 

    - name: Upload CryptographyHelper
      uses: actions/upload-artifact@v4
      with:
        name: CryptographyHelper
        path: src/CryptographyHelper/CryptographyHelper/bin/Release/*.nupkg
